---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-config-v1
  namespace: monitoring
  annotations:
    nfs.io/storage-path: "grafana"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-provisioner
