---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: theme-park
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    image:
      repository: ghcr.io/onedr0p/theme-park
      tag: 1.13.6@sha256:37a9266f24f6ab5a0d273db12156cf775a78970df00c7cb6b09216e4a9fbd299

    nameOverride: "theme-park"

    env:
      TZ: "${TZ}"

    service:
      main:
        ports:
          http:
            enabled: true
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:

        hosts:
          - host: &host "theme-park.${SECRET_DOMAIN}"
            paths:
              - path: /

        tls:
          - hosts:
              - *host
