---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: your-spotify-client
  namespace: home
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: yooooomi/your_spotify_client
      pullPolicy: IfNotPresent
      tag: latest@sha256:d02ceb96256209835f990cb2b233a2a6048c6308c333f2891850236d3aacf6ed

    dependsOn:
      name: your-spotify-server
      namespace: home

    env:
      TIMEZONE: ${TIMEZONE}
      API_ENDPOINT: https://spotifyapi.${SECRET_DOMAIN}

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "tunnel.${SECRET_DOMAIN}"
        hosts:
          - host: &your-spotify-client-host "spotify.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *your-spotify-client-host
