---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: miniflux
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: miniflux-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Miniflux
        ADMIN_USERNAME: "{{ .ADMIN_USERNAME }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        DATABASE_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@10.0.16.16:5431/miniflux?sslmode=disable"
        OAUTH2_CLIENT_SECRET: "{{ .MINIFLUX_OAUTH_CLIENT_SECRET }}" # from authelia
        # Postgres Init
        POSTGRES_DB: miniflux
        POSTGRES_HOST: 10.0.16.16
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        PGPORT: "5431"
  dataFrom:
    - extract:
        key: miniflux
    - extract:
        key: postgres
    - extract:
        key: authelia
