---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./helm-release.yaml
  - ./pvc.yaml
commonLabels:
  app.kubernetes.io/name: esphome
  app.kubernetes.io/instance: esphome