---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cilium-app
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/cilium/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
