---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app smtp-relay
  namespace: home
spec:
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  maxHistory: 2
  timeout: 20m
  install:
    remediation:
      retries: 300
  upgrade:
    remediation:
      retries: 300
  values:
    fullnameOverride: *app
    env:
      SMTP_SERVER: smtp.sendgrid.net
      # OVERWRITE_FROM: "${SECRET_SENDGRID_USER_SMTP_RELAY}"
      SMTP_USERNAME: apikey
      SMTP_PASSWORD: "${SECRET_SENDGRID_APIKEY_SMTP_RELAY}"
      SERVER_HOSTNAME: "${SECRET_DOMAIN}"
    image:
      repository: docker.io/juanluisbaptiste/postfix
      tag: 1.7.1
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SVC_SMTP_RELAY_ADDR}
        externalIPs:
          - "${SVC_SMTP_RELAY_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 25
