---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: web
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: ghost
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: k8sathome
        namespace: flux-system
      interval: 5m
  interval: 15m
  maxHistory: 2
  timeout: 20m
  install:
    remediation:
      retries: 300
  upgrade:
    remediation:
      retries: 300
  values:
    image:
      repository: ghost
      tag: 5.33@sha256:b1d760283b41873306afb9107ae56d53d0db701182100a6f94a629977f715390
    env:
      TZ: "${TZ}"
      url: "https://${SECRET_GHOST_DOMAIN}"
      database__client: mysql
      database__connection__host: ${SECRET_MARIADB_SERVER}
      database__connection__user: ${SECRET_GHOST_MARIADB_USER}
      database__connection__password: ${SECRET_GHOST_MARIADB_PASS}
      database__connection__database: ${SECRET_GHOST_MARIADB_DB}
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "post"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "tunnel.${SECRET_DOMAIN}"
        hosts:
          - host: "${SECRET_GHOST_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "${SECRET_GHOST_DOMAIN}"
            secretName: "ghost-tls"
    persistence:
      content:
        enabled: true
        existingClaim: ghost-v1
    mariadb:
      enabled: false
