---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-v1
  namespace: web
  annotations:
    nfs.io/storage-path: "ghost"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-provisioner
