---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tailscale-relay
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/tailscale-relay/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: tailscale-relay
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 5m
