---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress_0
  namespace: web
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://groundhog2k.github.io/helm-charts/
      chart: wordpress
      version: 0.6.2
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: wordpress
      tag: 6.0.1-apache
    env:
      TZ: ${TZ}
    externalDatabase:
      host: ${SECRET_MARIADB_SERVER}
      name: ${SECRET_WP_0_MARIADB_DB}
      user: ${SECRET_WP_0_MARIADB_USER}
      password: ${SECRET_WP_0_MARIADB_PASS}
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
        hosts:
          - host: "${SECRET_WP_0_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "${SECRET_WP_0_DOMAIN}"
            secretName: "wordpress_0-tls"
    persistence:
      content:
        enabled: true
        existingClaim: wordpress_0-v1
    mariadb:
      enabled: false
