---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress_0-v1
  namespace: web
  annotations:
    nfs.io/storage-path: "wordpress_0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-provisioner
