---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paradoxalarminterface
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      git: git@github.com:wipash/charts
      ref: add-chart-paradoxalarminterface
      path: charts/stable/paradoxalarminterface
  install:
    disableWait: true
    remediation:
      retries: 100
    createNamespace: true
  upgrade:
    remediation:
      retries: 100
  # dependsOn:
  #   - name: mosquitto
  #     namespace: home
  values:
    env:
      TZ: "${TIMEZONE}"
    # ingress:
    #   main:
    #     enabled: true
    #     primary: true
    #     ingressClassName: "ingress-nginx"
    #     hosts:
    #       - host: &host "zigbee2mqtt.${SECRET_DOMAIN}"
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #     tls:
    #       - hosts:
    #           - *host
    persistence:
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: feature.node.kubernetes.io/usb-02_0451_16a8.present
    #               operator: In
    #               values:
    #                 - "true"
    securityContext:
      privileged: true
    podSecurityContext:
      supplementalGroups:
        - 20 # dialout for /dev/ttyUSB0
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
    config:
      # Minimal configuration.yml example
      SERIAL_PORT: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
