---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - helm-release.yaml
  - config-pvc.yaml
  - volsync.yaml
commonLabels:
  app.kubernetes.io/name: tautulli
  app.kubernetes.io/instance: tautulli
