---
creation_rules:
  # - path_regex: \.sops\.yaml$
  #   age: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
  - encrypted_regex: '^(data|stringData)$'
    age: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
