# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops
    namespace: flux-system
stringData:
    adminPassword: ENC[AES256_GCM,data:mX99pktosrS4a6itdLR+9vs=,iv:gEi8f7Dns8QE10ZMlpeOy4hKu5UIhpVRU1QBuIKZbEE=,tag:bQmxS6HG94lccOd+JMHCuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdzFhNU4va0c3aWNWYSti
            cHc1QmdwQlQ5Z3hvbHZHZWFvaXhWV3Q2eWdzClo5bnhOaEwwTHFUOFNFTkJZNlVt
            Q0E0eVRVOEM0L1NnNTY5TkNvc3ZUOTQKLS0tIFFUL1NraVFGMVdRVGIzM3hlWHR2
            bDRLT0Q2d0pvOEloQnFlS2ZOeHkwbUkKgFV/5UiDnBy1QHcfCo6sdg2tva4dyTxC
            rMYY/Dcn5UMFdgiJpYgg4pSuUAi/yhGalHbOYwxKqXJdLst9VCBOjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T20:55:28Z"
    mac: ENC[AES256_GCM,data:FEePS0aWu8bQTRloeAx0JxdsYT+kuT/JwCCd/y6UnJ4ht2sYkYIrzsGlTWdpCLk1zVTiP5yWZcTy83jrWQzo49gNIYGn5R7OFgyRryW/hFUzcHDD+kyULiVydvP9ungjY5QxFMH3q341/VTncL2fvz0FZX5+zDqicwyh6yHcgg4=,iv:9jkHkjcOXq4Cn2Rzdehn8u+OiSEH2UYX+6aaqkAxs30=,tag:R3d85nKGnRfoll0QDKnWsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
