---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.kubito.dev
      chart: cloudflared
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: kubito
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/milgradesec/cloudflared
      tag: 2022.7.1
    replicaCount: 3
    tunnelID: ${SECRET_CLOUDFLARE_TUNNEL_ID}
    existingSecret: cloudflare-tunnel-credentials
    ingress:
      - hostname: "*.${SECRET_DOMAIN}"
        service: https://ingress-nginx.networking
        originRequest:
          noTLSVerify: true
      - service: http_status:404
