---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: your-spotify-server
  namespace: home
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: yooooomi/your_spotify_server
      pullPolicy: IfNotPresent
      tag: latest@sha256:627ea442517c5236d7236a8dbcec29135011f75c6c7998f8ee8734d25f98b997

    dependsOn:
      name: your-spotify-mongo
      namespace: home
    env:
      TIMEZONE: ${TIMEZONE}
      API_ENDPOINT: https://spotifyapi.${SECRET_DOMAIN}
      CLIENT_ENDPOINT: &client-url https://spotify.${SECRET_DOMAIN}
      SPOTIFY_PUBLIC:
        secretKeyRef:
          name: your-spotify
          key: client-id
      SPOTIFY_SECRET:
        secretKeyRef:
          name: your-spotify
          key: secret
      MONGO_ENDPOINT: mongodb://your-spotify-mongo.home.svc.cluster.local:27017/your_spotify
      CORS: *client-url

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "tunnel.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://spotify.${SECRET_DOMAIN}"

        hosts:
          - host: &your-spotify-server-host "spotifyapi.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *your-spotify-server-host

    podAnnotations:
      secret.reloader.stakater.com/reload: your-spotify
