# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: core
stringData:
    cloudflare-token: ENC[AES256_GCM,data:WSdPQO7oSQXR/2GM1Qt8varmhhleDi+mwdIC2lANQCf5bjyJJTUi+A==,iv:/KrFhjn1/MfyYLKpsh9UwS/qCKB9+PLrUuJJX8XKD3s=,tag:DV23n4z7SSFWOQ/6Km6VkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhd3pyamJIcHdpaTdQelZl
            WXNEMzhDcVgyOVZISnRndGlCYWFYZGRVMjNVClpxLytZL0tqYWcwNGt4UXd4amtW
            QWhZS3Q0bHQzR2hYd2MyNnZ6YngwQlEKLS0tIDNpa2VoTGt0UkFGQVdGbk9tZWEz
            WDN6eEgyNm1VSDdad0F0UEFoaFhWMTAKe4SEN8ePPiIF+d7Gh8lWB2lET+SafaFT
            e/5pCsMTYHnf8O2zaUblZ6aeHx01qtvfQaUWEQwCbmtsG7fIH3hnsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-26T01:11:12Z"
    mac: ENC[AES256_GCM,data:CZdHM6PKUE0kzQKdiBmvoTkVI1DTgfq28fZiRHN3CvUmRgK1BMIuP9iutFreZYzReTb99GWR7xvxxQuVgPFKhN9q7QoVdOjej1VTjYvAiPvZBe4RPzxGuH9F4igqZTPCQZ1BX0o+/dX0jo62x97R9EV1YpYNjCSlX6dRSe6yN7g=,iv:rar3VozJLyfUBQ7chEada5Q30T4KqcO0GC6eWjr60Ik=,tag:6gRP9x4Q2vZ0ZTt290SEJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
