# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:JB9fWk/8b/HvK0oFYuViNAMOctR/PwlmuPH/KM1uxkydvMfqTK8t5w==,iv:l4JN6t6+G1QxgAu7LkxZfT8XtZOXFZ9xwNnbVOnv32w=,tag:NU3OKAg32pZbrhyNCpCd3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK2F0WlFRSWo5UFZ4OHZz
            WENxRFN6eEpyT3hsc3hlWm4yOXFYeTFSZHdnCnJyYWNEZ2liaGVCbXBEYTkwckly
            QjcvZ0NpWm9hVHNPaXdGN2IweS9CM00KLS0tIENYdFJvbXJMWW9iZjVjOHhtZzhR
            SGtVUUl6OEZGZHdFblJMcFczSUsxTVEKWykfKcVspbRk9+adRC058LapK4g5zlk7
            bFu38dH06T0oHv60zS33+aFaOMmAnRz3R62eOstAaKYBg49Ygdul1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-24T05:03:47Z"
    mac: ENC[AES256_GCM,data:p1xyXO7T5M+/OqlgOMKNbGzivnz8udByBOQAS8VY5o2q+niQmwlMyhZVTqIIAhP0RjhuWuBnWUrXKVscsGC3KqhKgBUBUoBar5uZ/yDBPtjDh1n88GvIUvV5SmXNJIflKqutqjaxv+kw+BfMaRS7z3s/rsOqpgQcSbSA5kLgo+8=,iv:aXnhpotA27HviUSGFGijePhOdQXXc0Zb7ropvktCKI8=,tag:b5GTL5LHLi4A6hWWO1TjZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
