---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adminer
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://cetic.github.io/helm-charts
      chart: adminer
      version: 0.1.7
      sourceRef:
        kind: HelmRepository
        name: cetic
        namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: adminer
      tag: 4.8.1-standalone
      pullPolicy: IfNotPresent
    config:
      design: dracula
      externalserver: ${SECRET_MARIADB_SERVER}
      plugins: "tables-filter tinymce designs"
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - host: &host "adminer.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: "wildcard-tls"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: database-cog
        hajimari.io/appName: Adminer
        hajimari.io/group: Database
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
