---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./helm-release.yaml
  - ./pvc.yaml
commonLabels:
  app.kubernetes.io/name: unifi
  app.kubernetes.io/instance: unifi
