---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config-v1
  namespace: networking
  annotations:
    nfs.io/storage-path: "unifi"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-provisioner
