---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app n8n
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: docker.io/n8nio/n8n
      tag: 0.201.0

    dnsConfig:
      options:
        - name: ndots
          value: "1"

    # podAnnotations:
    #   secret.reloader.stakater.com/reload: n8n-secrets

    env:
      GENERIC_TIMEZONE: ${TZ}
      N8N_PROTOCOL: "https"
      N8N_PORT: &port 443
      N8N_HOST: "n8n.${SECRET_DOMAIN}"
      WEBHOOK_URL: https://n8n.${SECRET_DOMAIN}
      N8N_EDITOR_BASE_URL: https://n8n.${SECRET_DOMAIN}
      N8N_LOG_LEVEL: info
      N8N_LOG_OUTPUT: console
      N8N_VERSION_NOTIFICATIONS_ENABLED: false
      N8N_DIAGONISTICS_ENABLED: false
      N8N_HIRING_BANNER_ENABLED: false
      EXECUTIONS_DATA_PRUNE: true
      EXECUTIONS_DATA_MAX_AGE: 336

    # envFrom:
    #   - secretRef:
    #       name: n8n-secrets

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: source-branch
          hajimari.io/appName: n8n
        hosts:
          - host: &host "n8n.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: n8n-v1
        mountPath: /home/node/.n8n
