---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paradox-alarm-interface
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    initContainers:
      01-init-config:
        image: ghcr.io/onedr0p/alpine:3.17.2@sha256:5d973006bf93ba66e38758694dfed6df091a13e712b6a075f7ed7bb6fd8c2189
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["echo 'Running' && envsubst < /data/pai.conf > /etc/pai/pai.conf && cat /etc/pai/pai.conf >> /proc/1/fd/1 && tail -f /dev/null"]
        env:
          - name: MQTT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mosquitto-secret
                key: username
          - name: MQTT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mosquitto-secret
                key: password
        volumeMounts:
          - name: config
            mountPath: /etc/pai
          - name: config-file
            mountPath: /data/pai.conf
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: paradoxalarminterface/pai
      tag: 3.2.1
    env:
      TZ: "${TIMEZONE}"
    persistence:
      config-file:
        enabled: true
        type: configMap
        name: paradox-alarm-interface-configmap
        subPath: pai.conf
        mountPath: /data/pai.conf
        readOnly: true
      config:
        enabled: true
        type: emptyDir
        mountPath: /etc/pai
      serial:
        enabled: true
        type: hostPath
        hostPath: /dev/serial
        hostPathType: Directory
        mountPath: /dev/serial
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/usb-ff_10c4_ea60.present
                  operator: In
                  values:
                    - "true"
    securityContext:
      privileged: true
    podSecurityContext:
      supplementalGroups:
        - 20 # dialout for /dev/ttyUSB0
    service:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    nodeSelector:
      siliconlabs.feature.node.kubernetes.io/cp2102: "true"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
