---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./nodefeaturerule.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: paradox-alarm-interface-configmap
    files:
      - pai.conf=./config/pai.conf
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
labels:
  - pairs:
      app.kubernetes.io/name: paradox-alarm-interface
      app.kubernetes.io/instance: paradox-alarm-interface
