# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: networking
stringData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:RC6Tqt4/mWeVA4ncdsaGFVvEJtpQ4YC5Rh122RLRVfTVZpPrddSq4A==,iv:EYFJiAmlYCx7ix9vnC7lL6RhfVibuB6dft729GQEra0=,tag:eQxHFd8tCbltWmsWg46PLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByampOKzVkUnlGV0hzd2Qz
            SnBZNUJGWThVQVExK0NuMkFBTEtNUUF6V21zCmNKSFhoL3lkaUltTWhOWHNUaWlQ
            ZXZqSWQrQmVkV2orektEY0RSOXV5N1EKLS0tIFVldU43SVEyaHZpNUhoZU9LZGhP
            Z1dyYTRYZ21PeDV6TTVYK04zTURFVWcKB6F+B5bfaMKSrzwOt3QzUPmFnGHk1yj8
            ZD424LfAkKK4YhaUFCKhqwWN0qgoxyr8sMIZmkpfybGa1ul+hcPTaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-14T01:42:07Z"
    mac: ENC[AES256_GCM,data:XyraYJoaxp6KjrZX2adVbRBrYK7QEthVT77neEmSZwcfu/O1lKGrNFnpf8Tct0m61N0i7u9nLzH2LYr2Q2zBNeDiA46R/zrWfLfssXVDPSxcuMW8ubFu/CwzSI1pfxwa3YpWdZvUuwx57/Hm4EmFdSk4TBynn/QkUqtNrz4PgTI=,iv:w+sjLE+C/8jMeJ4y8PgMHas0F0OV/O4TmWYm+PhMVzI=,tag:GtpBuIF7uKJABKzIYFNDlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
