---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 10.5.2
      sourceRef:
        kind: HelmRepository
        name: k8sathome
        namespace: flux-system
      interval: 5m
  interval: 15m
  maxHistory: 2
  timeout: 20m
  install:
    remediation:
      retries: 300
  upgrade:
    remediation:
      retries: 300
  values:
    image:
      repository: spx01/blocky
      tag: v0.19
    controller:
      strategy: RollingUpdate
      replicas: 2
    replicas: 2
    env:
      TZ: ${TZ}
    service:
      main:
        ports:
          http:
            port: 4000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${METALLB_BLOCKY_ADDR}
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
        externalTrafficPolicy: Local
      dns-udp:
        enabled: true
        nameSuffix: dns-udp
        type: LoadBalancer
        loadBalancerIP: ${METALLB_BLOCKY_ADDR}
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
    config: |
      upstream:
        default:
        - tcp+udp:8.8.8.8
        - tcp+udp:8.8.4.4
        - tcp+udp:1.1.1.1
        - tcp-tls:1.0.0.1:853
        - https://cloudflare-dns.com/dns-query
      # conditional:
      #   mapping:
      #     ${SECRET_DOMAIN_INTERNAL}: tcp+udp:${GATEWAY_ADDRESS}
      #     local: tcp+udp:${GATEWAY_ADDRESS}
      customDNS:
        mapping:
          k3s.${SECRET_DOMAIN}: ${METALLB_INGRESS_ADDR}
          alert-manager.${SECRET_DOMAIN}: ${METALLB_INGRESS_ADDR}
          mealie.${SECRET_DOMAIN}: ${METALLB_INGRESS_ADDR}
          nodered.${SECRET_DOMAIN}: ${METALLB_INGRESS_ADDR}
          pgadmin.${SECRET_DOMAIN}: ${METALLB_INGRESS_ADDR}
          prometheus.${SECRET_DOMAIN}: ${METALLB_INGRESS_ADDR}
          zigbee.${SECRET_DOMAIN}: ${METALLB_INGRESS_ADDR}
          phpmyadmin.${SECRET_DOMAIN}: ${METALLB_INGRESS_ADDR}
          hajimari.${SECRET_DOMAIN}: ${METALLB_INGRESS_ADDR}
          dash.${SECRET_DOMAIN}: ${METALLB_INGRESS_ADDR}
          monica.${SECRET_DOMAIN}: ${METALLB_INGRESS_ADDR}
        ##
          3dp.${SECRET_DOMAIN}: ${EXTERNAL_TRAEFIK_ADDR}
          3dp.${SECRET_DOMAIN_INTERNAL}: 10.0.10.148
          hass.${SECRET_DOMAIN}: ${EXTERNAL_TRAEFIK_ADDR}
          hass.${SECRET_DOMAIN_INTERNAL}: 10.0.16.3
          seave.${SECRET_DOMAIN_INTERNAL}: 10.0.16.10
          ${SECRET_NAS_HOSTNAME}: ${SECRET_NAS_IP}
          unifi.${SECRET_DOMAIN}: ${GATEWAY_ADDRESS}
          unifi.${SECRET_DOMAIN_INTERNAL}: ${GATEWAY_ADDRESS}
          traefik.${SECRET_DOMAIN}: ${EXTERNAL_TRAEFIK_ADDR}
          traefik.${SECRET_DOMAIN_INTERNAL}: ${EXTERNAL_TRAEFIK_ADDR}
          traefik.dmz.${SECRET_DOMAIN_INTERNAL}: ${EXTERNAL_TRAEFIK_ADDR}
          docker1.${SECRET_DOMAIN_INTERNAL}: 10.0.16.245
          sk1.${SECRET_DOMAIN_INTERNAL}: 10.0.16.11
          #
          sonarr.${SECRET_DOMAIN}: ${EXTERNAL_TRAEFIK_ADDR}
          radarr.${SECRET_DOMAIN}: ${EXTERNAL_TRAEFIK_ADDR}
          nzbget.${SECRET_DOMAIN}: ${EXTERNAL_TRAEFIK_ADDR}

      blocking:
        blockType: zeroIp
        failStartOnListError: true
        blackLists:
          ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - http://sysctl.org/cameleon/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
          kids:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
          - https://raw.githubusercontent.com/wipash/homelab/master/cluster/workloads/networking/blocky/whitelist.txt
        clientGroupsBlock:
          default:
          - ads
      clientLookup:
        upstream: tcp+udp:${GATEWAY_ADDRESS}
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
    probes:
      liveness:
        failureThreshold: 5
        periodSeconds: 10
      readiness:
        failureThreshold: 5
        periodSeconds: 10
      startup:
        initialDelaySeconds: 5
        failureThreshold: 30
        periodSeconds: 10
    prometheus:
      serviceMonitor:
        enabled: true
    tolerations:
      - key: "arm"
        operator: "Exists"
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 500Mi
