---
apiVersion: batch/v1
kind: Job
metadata:
  name: "listlocks-${rsrc}-${ts}"
  namespace: "${namespace}"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: listlocks
          image: docker.io/restic/restic:0.14.0
          args: ["list", "locks", "--no-lock", "--verbose"]
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop: ["ALL"]
          envFrom:
            - secretRef:
                name: "${rsrc}-restic-secret"
