---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monica
  namespace: home
spec:
  releaseName: monica
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: monica
      version: 8.1.2
      sourceRef:
        kind: HelmRepository
        name: k8sathome
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: monica
      tag: 3.7.0-apache

    env:
      APP_URL: https://monica.${SECRET_DOMAIN}
      APP_ENV: production
      APP_KEY: ${SECRET_MONICA_APP_KEY}
      DB_HOST: ${SECRET_MARIADB_SERVER}
      DB_DATABASE: ${SECRET_MONICA_MARIADB_DB}
      DB_USERNAME: ${SECRET_MONICA_MARIADB_USER}
      DB_PASSWORD: ${SECRET_MONICA_MARIADB_PASS}
      DEFAULT_MAX_STORAGE_SIZE: 4096
      MAIL_MAILER: smtp
      MAIL_HOST: smtp-relay.home
      MAIL_PORT: 25
      MAIL_FROM_ADDRESS: monica@${SECRET_DOMAIN_MAIL}
      MAIL_FROM_NAME: Monica
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host monica.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: monica-v1
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 250Mi
    mariadb:
      enabled: false
