---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-config-v1
  namespace: home
  annotations:
    nfs.io/storage-path: "zigbee2mqtt"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-provisioner
