---
k3s_cluster:
  children:
    master:
      hosts:
        rpi1:
          ansible_host: "10.0.16.131"
    workers:
      hosts:
        rpi2:
          ansible_host: "10.0.16.132"

network:
  hosts:
    udm:
      ansible_user: root
      ansible_host: "10.0.16.1"
