---
kubernetes:
  children:
    master:
      hosts:
        rpi1:
          ansible_host: "10.0.16.131"
    worker:
      hosts:
        rpi2:
          ansible_host: "10.0.16.132"

network:
  hosts:
    udm:
      ansible_user: root
      ansible_host: "10.0.16.1"
      ansible_ssh_extra_args: "-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedKeyTypes=+ssh-rsa"
