---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: ${GATEWAY_ADDRESS}
        peer-asn: 65510
        my-asn: 65511
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - ${NETWORK_BGP_SVC_CIDR}
        avoid-buggy-ips: true
