---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: 10.0.16.1
        peer-asn: 65510
        my-asn: 65511
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 172.16.10.0/24
        avoid-buggy-ips: true
