# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    TIMEZONE: ENC[AES256_GCM,data:Sbend876CaUFY1kc+tJkKg==,iv:LEMnFqnq/p6xj5PQnzTRA6dyDWzx7rmpO1SOzfTAzDc=,tag:zLqZYHmNo9Go6xUcfRIeZA==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:xfndmBx7tnF8Ei/fSJZN,iv:i/p9H5bwIA89HFVZSdtPP0L0L6zU/SrkbnsjNXyXFPI=,tag:bhRsvUEeIsgxaPbcAz2b6A==,type:str]
    SECRET_EMAIL_CLOUDFLARE: ENC[AES256_GCM,data:z6rHn1Esq4aCLUobTZjBQCOdww==,iv:pK4eN6WSc6MfdtdKiXtzNvQbr3BYqceYhhoLgz8fE0k=,tag:YKX+ifzBgT3wpDlzLHigbg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:SF3htw+YXOxPIQ==,iv:NWCML1n9m/VcRzTytlTaD6fU80TbtkSoR5DDhy0JPvA=,tag:LQ7O8D+SQ8cMb78iXdzllA==,type:str]
    SECRET_DOMAIN_INTERNAL: ENC[AES256_GCM,data:t/QeVv5VU4rxtHIQcQ==,iv:3IU95LHBfOeJukqAyM9/aDuzJHtbPYOpPMWHXZhFzZA=,tag:UhHBMVgQ9wqYyQooiFekUg==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:0aTVxACdguoPncFejeyYrCy9ZA==,iv:A8bvGIIYlZ7NctEaANrqtf3E5zihk2GLE0HEXOvEhwA=,tag:nnh5yCYopKO1yLx9QTebjg==,type:str]
    SECRET_NFS_SERVER_PATH: ENC[AES256_GCM,data:VpGHKDMUEx5rI/5B,iv:BJODxPPcGKpbvz36xKhqKwzsaCa3QysKQ78HNG7RFOc=,tag:SjL5B8RrP0xRWPL7PuwwRQ==,type:str]
    SECRET_POSTGRES_SERVER: ENC[AES256_GCM,data:7bskI9Uo9kQG1cGMTDit+NCSJg==,iv:yvM0rOTywSPhu9NOS27SXYV/POpRHygKgBymTFo7TqQ=,tag:L3FZM0kZyVWVvCGShptp5w==,type:str]
    SECRET_POSTGRES_SERVER_SUPERUSER: ENC[AES256_GCM,data:eShJdvhgLLY=,iv:BS9H0iRHrhkfCOfbmdW9JmDxmR+KpC9YpERgzkmBXAM=,tag:VHmpHhX7AZGcVD4kwriPrw==,type:str]
    SECRET_PGADMIN_EMAIL: ENC[AES256_GCM,data:CvvVPb+ElBN0td1u6VoV,iv:5mdxYdlUg7cy1B2nxPf6UuMbGeyRnfGFcqmkEPLYW2k=,tag:SQii0mDAkgp1wE716NyAnA==,type:str]
    SECRET_PGADMIN_PASSWORD: ENC[AES256_GCM,data:TMrWwwuOfnQNQ33EOxbMO/YifMo=,iv:UdzflziOU7aSUnekJXsXAqFR3zTxhBj/XVI+j2ERDP4=,tag:WxcgrkvnVEFNcYhNhXWoHQ==,type:str]
    SECRET_MEALIE_PG_SERVER: ENC[AES256_GCM,data:lzzgBARJsMPtwLegRzyfwXCdxw==,iv:w9TYeGLis9ZnFYQg6u9t4kYojJQTIPRjQAIDmE/Bjbs=,tag:IyJKwC/WLV5x6xTromhOZA==,type:str]
    SECRET_MEALIE_PG_DB: ENC[AES256_GCM,data:SL3832Or,iv:eVUgwGnF+Rl3r67nPkQnRNHyuDCwikqQyNN16uLwd8w=,tag:BCthIwUzbSs+5OA54m/cWQ==,type:str]
    SECRET_MEALIE_PG_USER: ENC[AES256_GCM,data:HrJyJgHY,iv:i5pz24oIPWSehjTDZj1P1w1WGYBItM6gzhD3IY3ETwc=,tag:ZTVlvguNUApQfqRN7G02pg==,type:str]
    SECRET_MEALIE_PG_PASS: ENC[AES256_GCM,data:WlHWkxNq+1JGeO2Kt1Z36rwAHro=,iv:KNDpnqEA7Qdjfx39aLHB/qbufUPuhN81pZBPPq7Tw48=,tag:oaMHn4NspjU5Mgtr0pxvQQ==,type:str]
    SECRET_MARIADB_SERVER: ENC[AES256_GCM,data:K9Mz6znEktgctQcSZTmKYTP89g==,iv:sKwVC6+XksinX3o/vW1LqxO92q8/XdE9cjxLaaLc7uM=,tag:5H8duZJSuAxqqvULCB3/mg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:QI+sWHJYAlmwQ5inIIhlzJJuV0PaoHuRDrYv2FO29MzK2JYV,iv:1bqrGJ4qb2ceTqiaob60vTZBPFbdqqkz3fOZ0qM77Og=,tag:KzpZrfJJfkg96Ja/XgbdCA==,type:str]
    SECRET_MQTT_SERVER: ENC[AES256_GCM,data:72genyKfH7/b28C5C+uJeLD6,iv:dmyGCjFhj6J4cpeIUx+YJ1z/GW0Xb/0RULnm4qvnjYA=,tag:GMRbLbCtvMSrQxEjaMUHVA==,type:str]
    SECRET_MQTT_USER: ENC[AES256_GCM,data:KAQsVQ==,iv:Vk3BQIFf7nmSSiTD1PmYOIG/gfmG7mcKlpuztVlYrDc=,tag:ePdQXsErGSp2bCKDNxwwAg==,type:str]
    SECRET_MQTT_PASS: ENC[AES256_GCM,data:mn8DECyXyd3udM+RsGs0,iv:ZtG+K2QjIFyKPKx18CtNiIEITJdXnqT8j4Y8pBOexcg=,tag:X9NKyNtd7FU/wZ7wb8HbgQ==,type:str]
    SECRET_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:GheZ1yG46vkhGckJfBZJn9zQ8PJhM/RD8eWnGbxK,iv:445vlBiThZ9dNis0XjuaaDW+K67MBXFtQZbPrC5LVxQ=,tag:8UOp0/n1LhKkbQqUuy+P5Q==,type:str]
    SECRET_PUSHOVER_PROMETHEUS_APP_KEY: ENC[AES256_GCM,data:g3tDJc3Fk/KkK4jnoA9nGJ6NHfaP2Nz+AW9JsSVX,iv:wvCzfJ2x5nr6pdeOpfHr2t5FkUB7rhfBMRHowDF2yYg=,tag:WaKPaWgvEBuYup3uNArCwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISUpYRFp3UGtuOFpYcExJ
            SVBvUmdjY1NhcDh1M243eWRXMUh0cWtPbHk0CkNNVWVPVkRySWdtVjMrVDhOa2Q3
            YlRzQ3lwMUhiUVI0Zmk0VEk1RjE1bVEKLS0tIFcyOHdWeHBOQUh6M1h6QmVrZU5i
            OStHdFozd0M4TGRXa2VmSWI3bkpENXMKvGMMDFK0xldb7wOhrmDYN9kdZPpbfw0e
            Q9WRCCvLoY6s9a0EGB0OfI/ZlzRO/lXGh2Dxr7l4dpKIICmg2BzUAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-01T02:28:33Z"
    mac: ENC[AES256_GCM,data:7XyVZ/4c0dumwKXGNviZIrev/2j0mG9Fxs+6HHh7EncqRGJWQ80Jfjdh2twVbpfLwmaK0Po+Ps8BkUmUz1Dj2Sg9SJSWXKMfyncFe6y8pO7U/9o1WD2v1WaR1ArMh7sEAdetWTqSV1FRfLNopcuPSXX1el+dokJgzsc96raIAeY=,iv:gJoMsHQYkUuhIsfGquBsfxMh0Y2t3m9NogBDKCV3Gig=,tag:VM+zu21U59cjHCijLLlYzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
