# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    TIMEZONE: ENC[AES256_GCM,data:5E8POndXIQcIt7EzcArHlw==,iv:xPvNCkUTg+zOdlwlh9rbzICiGZQr8eI5vL8JUETOV/o=,tag:LxKHnFZEASgIABl3RWgdHw==,type:str]
    TZ: ENC[AES256_GCM,data:+gZkyhWoSDgdflWYFP6y+Q==,iv:Bj4MVNox17pjEzFRKFMjvT9QDBIY456yvvV8f7QLRSo=,tag:OPttGkJQ6igY/a6O4XUNEw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:+Rg/jy09gLHLcYiWRMSW,iv:tYsR0Wb17BfqyJVIcnrbaxL/rT40tJkiC0ndrl1SmDQ=,tag:Fch2CyF7RXnVe6ZSzkjCMQ==,type:str]
    SECRET_EMAIL_CLOUDFLARE: ENC[AES256_GCM,data:nATrV+1914mgf885czJvsP6rTw==,iv:Z6OoPMvnEq5MgnjD1kt0w3/chp+iJEW2wtUIgVKDpag=,tag:th2h+kJywADSMUkP0Y7HyQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:0eNrf62HlZ2ppQ==,iv:vauUkWQzvCx6saJx2GvYxODlZ57z5AdioNVtwNjmTcw=,tag:QNbG9xLsdo1q7aKMLVYBig==,type:str]
    SECRET_DOMAIN_INTERNAL: ENC[AES256_GCM,data:/zZ3fTZ6Ie5pWPGCBg==,iv:b+qsaPgdNN2TIy4en7nnlXH/td0zW9ifsuNxW8cPnfY=,tag:4NdZfzSNQhuH2X81U5OuKQ==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:UOcuw7yoO9VSswWkpa9P3U3hhA==,iv:j1aAkyeANuvv1KDS8WMB0dN7vL3ZakKyVlK+QBC4F78=,tag:hiE9n7OyEIMGYWDW7Xu6UQ==,type:str]
    SECRET_NFS_SERVER_PATH: ENC[AES256_GCM,data:L9C9UJdnUO+5enpH,iv:DAV9NCwyAnJTzq+BHYjWo/kHJqWCSK4bXhWm1GFS1Oo=,tag:03C/exxQ1moStYr7yacfBg==,type:str]
    SECRET_POSTGRES_SERVER: ENC[AES256_GCM,data:qe3rNe4SSXTuAd/TMASNdG9ViA==,iv:Q4Z78JW0A/sWyiYE6LqlyOMSKZOQ1V3ywQT+AxOHm9Q=,tag:H1/WOIj7Wu+9D8An1VEdaQ==,type:str]
    SECRET_POSTGRES_SERVER_SUPERUSER: ENC[AES256_GCM,data:WztjgvGsAjo=,iv:hnFgpNUZr/S0+cgVrBYIL+aYknIcG32xgTLAuB804MQ=,tag:pdRWvk7l/VZe7G+bSpDbVg==,type:str]
    SECRET_PGADMIN_EMAIL: ENC[AES256_GCM,data:0vBGIsnbY7MN0f0PcFpN,iv:kEqlwcKqycwmZW7wqAApVBN3QCDUgZTs8bhRhqBfrfI=,tag:pzkd5UPhvq3Z4PJI7sbBOA==,type:str]
    SECRET_PGADMIN_PASSWORD: ENC[AES256_GCM,data:2SYbr3TxI+zCca4466ZfzDGNlNg=,iv:9Ir2+JjFfXxJJFVOT0d1dYl38I5Ghs6bmlcBCaO9p28=,tag:425gliCHin9cha/Zaz0IGg==,type:str]
    SECRET_MEALIE_PG_SERVER: ENC[AES256_GCM,data:NiFqTJrQR9uQWGgd09HGWXSPkQ==,iv:ypr8xQA113+tx+u4Kaa8fEPvRSxGV20GOipqgNljtCA=,tag:phut3+8qU655sZmZIS96mQ==,type:str]
    SECRET_MEALIE_PG_DB: ENC[AES256_GCM,data:8GQ3Urlz,iv:Vu51QUnyt/vhVRGhBsEGczwyZSAAZEm3jg/QX5/bZx4=,tag:LIhers1Sso8faFWkC/0iQA==,type:str]
    SECRET_MEALIE_PG_USER: ENC[AES256_GCM,data:dAe/5F2k,iv:+pK7AafsdnqT59HnnQwGw0hvoIuAxNAZb/UTjmnaIf0=,tag:zD48XZCgpdU5mPR8iH5fwQ==,type:str]
    SECRET_MEALIE_PG_PASS: ENC[AES256_GCM,data:1BCgPBwUCpVpQRL6MauBaSTEB3U=,iv:GqvT1b00hF+SLTfiFIF10nMj35ZbQzpQwsEhJ36yXE8=,tag:Hu8UWOlv0IrlJWUMDi/qYw==,type:str]
    SECRET_MARIADB_SERVER: ENC[AES256_GCM,data:Of9xvjroKWQ5T6YSo0/JWfKv1Q==,iv:QipleEUGlbMeVE40G6nBbMuDDbbhi8aohpm3E8FN4tQ=,tag:DcbIDEYYKlHRQz1AQttztg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:okcOHa94hiUUaqP0VGeahhnqDotQ/av4Qsm1Ow5gS2JDuDUo,iv:c/OFjKjBEfe2HDGVtnFz9BDsOlLJpmg7/5kR0bi9iQo=,tag:DAnP8rWHiyFiRP1Sll5/Zw==,type:str]
    SECRET_MQTT_SERVER: ENC[AES256_GCM,data:TjZUnthujRkLtCwfgkVEud8Z,iv:9e3mf6QhEPywr/zwSYcJ34AwDadt8/LlGuuCrENfvQI=,tag:OTFVWKI6rCpXH/2PMbZ8pQ==,type:str]
    SECRET_MQTT_USER: ENC[AES256_GCM,data:va2UbQ==,iv:6DiKIUXUHtEkpQpJWmNkqhNzuA+P3VXQp6dMvKrXADI=,tag:FpBmXAB0LXE1Fl0jVRYzRg==,type:str]
    SECRET_MQTT_PASS: ENC[AES256_GCM,data:l1Xd9aIInmTA+Zm2ICg3,iv:rH7sBl9B8xXOkcP4lL7qHZ18oUnYXaJzsTxXTeFhWik=,tag:FsO3UKwfSVSwcx0J4htAyg==,type:str]
    SECRET_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:0g2QZf+KtypVdAO16q4oMf8okD45dSdqH5Liql0Z,iv:LX3g0/HZM/q5nt7ltQCiW+zY6NYySoQuqT8kUdqxFkw=,tag:Ist8nscr0AdQ5jeTrjFWrg==,type:str]
    SECRET_PUSHOVER_PROMETHEUS_APP_KEY: ENC[AES256_GCM,data:SM/P9Ybq0XLUOiCVIg2i+Xnjh6QbDjcSwzFLsng/,iv:BV/Vi+/RHtOP9VMPWyskmniAlqVZQPD/ZGUkLUKF/BU=,tag:NBwbtAQuTWgJv+49VbTqsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNLzFBZVk3NE9CVE1YOVA3
            aEh0aW9TZHg4NWh2Qm01U2NsNFllbUlJOVY0CkthaTdrb2RCTDZJbktBa014bDVC
            ZG4vbWoxQnhBcW5YbzFRUkFobjBnbWMKLS0tIFNGaUV4cFVjaVpScmMremY3Qm1C
            NUxCRUF4WW9qc0ZuUFJxU2R3dGVaaWsKEzdD42tqdgaor2OHXUu1SfLKSQ7aXhgB
            gVcGhZXPU/m3gk+cAkL+XComMvdZwam11rWNFMaLQ34Jnj1BZDS/4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-03T08:05:13Z"
    mac: ENC[AES256_GCM,data:9xwsVmfTwzqBbzcAxQF5vM4ZIGZzrIS+5kvjm5RtNShXPFncasTZZpZ69XkH+c+7iAzBIuC867KRFeXJpvPZk+tV8LIEeLuTgd75eIYYY51it6CnPFkapsKAnn2svDi1HZ7aKXBDVzG2JVZ//XrUZuScWANLzpCDmEAo7cPqLDo=,iv:vBoVK8O1Wz+GfRpmgku8ABDeNJFLuTBOyTu8/COtTmA=,tag:qfFb8rM1jVtq5LVMlj4+xA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
