---
apiVersion: v1
kind: Namespace
metadata:
  name: my-privileged-namespace
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: disk-wipe-talos-hp1
#   namespace: my-privileged-namespace
# spec:
#   restartPolicy: Never
#   nodeName: hp1
#   containers:
#     - name: disk-wipe
#       image: rook/ceph:v1.10.11
#       securityContext:
#         privileged: true
#       command:
#         [
#           "/bin/sh",
#           "-c",
#           "sgdisk --zap-all /dev/disk/by-id/ata-Samsung_SSD_860_EVO_500GB_S3YANB0M116883P",
#           "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/disk/by-id/ata-Samsung_SSD_860_EVO_500GB_S3YANB0M116883P",
#           "blkdiscard /dev/disk/by-id/ata-Samsung_SSD_860_EVO_500GB_S3YANB0M116883P",
#           "partprobe /dev/disk/by-id/ata-Samsung_SSD_860_EVO_500GB_S3YANB0M116883P",
#         ]
#       volumeMounts:
#         - mountPath: /dev
#           name: dev
#   securityContext:
#     runAsUser: 0
#     runAsGroup: 0
#   volumes:
#     - name: dev
#       hostPath:
#         path: /dev
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: disk-wipe-talos-lappy1
#   namespace: my-privileged-namespace
# spec:
#   restartPolicy: Never
#   nodeName: lappy1
#   containers:
#     - name: disk-wipe
#       image: rook/ceph:v1.10.11
#       securityContext:
#         privileged: true
#       command:
#         [
#           "/bin/sh",
#           "-c",
#           "sgdisk --zap-all /dev/disk/by-id/nvme-SAMSUNG_MZVLB512HAJQ-000H1_S3WTNX0M227157",
#           "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/disk/by-id/nvme-SAMSUNG_MZVLB512HAJQ-000H1_S3WTNX0M227157",
#           "blkdiscard /dev/disk/by-id/nvme-SAMSUNG_MZVLB512HAJQ-000H1_S3WTNX0M227157",
#           "partprobe /dev/disk/by-id/nvme-SAMSUNG_MZVLB512HAJQ-000H1_S3WTNX0M227157",
#         ]
#       volumeMounts:
#         - mountPath: /dev
#           name: dev
#   securityContext:
#     runAsUser: 0
#     runAsGroup: 0
#   volumes:
#     - name: dev
#       hostPath:
#         path: /dev
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-talos-lappy2
  namespace: my-privileged-namespace
spec:
  restartPolicy: Never
  nodeName: lappy2
  containers:
    - name: disk-wipe
      image: rook/ceph:v1.10.11
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "sgdisk --zap-all /dev/disk/by-id/nvme-SAMSUNG_MZVLW512HMJP-000H1_S36ENB0JB36275",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/disk/by-id/nvme-SAMSUNG_MZVLW512HMJP-000H1_S36ENB0JB36275",
          "blkdiscard /dev/disk/by-id/nvme-SAMSUNG_MZVLW512HMJP-000H1_S36ENB0JB36275",
          "partprobe /dev/disk/by-id/nvme-SAMSUNG_MZVLW512HMJP-000H1_S36ENB0JB36275",
        ]
      volumeMounts:
        - mountPath: /dev
          name: dev
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  volumes:
    - name: dev
      hostPath:
        path: /dev
