# Apply with
#  kubectl apply -f hack/wipe-rook-hp2-3.yaml

---
apiVersion: v1
kind: Namespace
metadata:
  name: my-privileged-namespace
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-rook-hp1
  namespace: my-privileged-namespace
spec:
  restartPolicy: Never
  nodeName: hp1
  containers:
    - name: disk-wipe
      image: rook/ceph:v1.10.11
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "sgdisk --zap-all /dev/disk/by-id/nvme-WD_PC_SN810_SDCPNRY-256G-1006_22341Q800595",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/disk/by-id/nvme-WD_PC_SN810_SDCPNRY-256G-1006_22341Q800595",
          "blkdiscard /dev/disk/by-id/nvme-WD_PC_SN810_SDCPNRY-256G-1006_22341Q800595",
          "partprobe /dev/disk/by-id/nvme-WD_PC_SN810_SDCPNRY-256G-1006_22341Q800595",
        ]
      volumeMounts:
        - mountPath: /dev
          name: dev
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  volumes:
    - name: dev
      hostPath:
        path: /dev
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-rook-hp2
  namespace: my-privileged-namespace
spec:
  restartPolicy: Never
  nodeName: hp2
  containers:
    - name: disk-wipe
      image: rook/ceph:v1.10.11
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "sgdisk --zap-all /dev/disk/by-id/nvme-WD_PC_SN810_SDCPNRY-256G-1006_22341Q807534",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/disk/by-id/nvme-WD_PC_SN810_SDCPNRY-256G-1006_22341Q807534",
          "blkdiscard /dev/disk/by-id/nvme-WD_PC_SN810_SDCPNRY-256G-1006_22341Q807534",
          "partprobe /dev/disk/by-id/nvme-WD_PC_SN810_SDCPNRY-256G-1006_22341Q807534",
        ]
      volumeMounts:
        - mountPath: /dev
          name: dev
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  volumes:
    - name: dev
      hostPath:
        path: /dev
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-rook-hp3
  namespace: my-privileged-namespace
spec:
  restartPolicy: Never
  nodeName: hp3
  containers:
    - name: disk-wipe
      image: rook/ceph:v1.10.11
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "sgdisk --zap-all /dev/disk/by-id/nvme-WD_PC_SN810_SDCPNRY-256G-1006_22341Q801193",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/disk/by-id/nvme-WD_PC_SN810_SDCPNRY-256G-1006_22341Q801193",
          "blkdiscard /dev/disk/by-id/nvme-WD_PC_SN810_SDCPNRY-256G-1006_22341Q801193",
          "partprobe /dev/disk/by-id/nvme-WD_PC_SN810_SDCPNRY-256G-1006_22341Q801193",
        ]
      volumeMounts:
        - mountPath: /dev
          name: dev
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  volumes:
    - name: dev
      hostPath:
        path: /dev
