---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app filebrowser-foundry
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/filebrowser
      tag: v2.23.0
    env:
      TZ: "${TZ}"
    service:
      main:
        ports:
          http:
            port: &port 80
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          auth.home.arpa/enabled: "true"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "tunnel.mcgrath.nz"
          hajimari.io/icon: mdi:folder-play-outline
        hosts:
          - host: &host "{{ .Release.Name }}.mcgrath.nz"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      foundry:
        enabled: true
        existingClaim: config-foundryvtt-0
        mountPath: /foundry
      filebrowser:
        enabled: true
        type: configMap
        name: filebrowser-config
        subPath: filebrowser.json
        mountPath: /.filebrowser.json
        readOnly: true
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block

    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - foundryvtt
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 500Mi
