---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grocy
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: linuxserver/grocy
      tag: version-v3.1.2
      pullPolicy: IfNotPresent

    env:
      TZ: "${TIMEZONE}"
      GROCY_CULTURE: "en_GB"
      GROCY_CURRENCY: "NZD"

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cart-variant"
          hajimari.io/appName: "Grocy"
        hosts:
          - host: &host "grocy.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: grocy-data-v1
