---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-data-v1
  namespace: home
  annotations:
    nfs.io/storage-path: "grocy"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-provisioner
