---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: &name firefly-iii-cron
  namespace: home
  labels: &labels
    app.kubernetes.io/name: firefly-iii
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  concurrencyPolicy: Forbid
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    metadata:
      labels: *labels
    spec:
      activeDeadlineSeconds: 120
      backoffLimit: 5
      template:
        metadata:
          labels: *labels
        spec:
          restartPolicy: Never
          containers:
            - name: *name
              image: curlimages/curl:latest@sha256:17468885fb8a20cd6bc25316f8267492c4d758ba63a6838ce74b9a0ffe4d2e90
              imagePullPolicy: IfNotPresent
              command:
                - /usr/bin/curl
              args:
                - --silent
                - --show-error
                - --fail
                - firefly-iii:8080/api/v1/cron/$(STATIC_CRON_TOKEN)
              env:
                - name: STATIC_CRON_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: firefly-iii-secrets
                      key: staticCronToken

          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - firefly-iii
                  topologyKey: kubernetes.io/hostname
