---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-config-v1
  namespace: home
  annotations:
    nfs.io/storage-path: "firefly-iii"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-provisioner
