---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app firefly-iii-data-importer
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m

  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    global:
      nameOverride: *app
    image:
      repository: fireflyiii/data-importer
      tag: version-0.9.17
    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "firefly-importer.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    dependsOn:
      - name: firefly-iii
        namespace: home

    env:
      TRUSTED_PROXIES: "**"
      FIREFLY_III_URL: "https://cash.${SECRET_DOMAIN}"
      VANITY_URL: "https://cash.${SECRET_DOMAIN}"
      FIREFLY_III_ACCESS_TOKEN:
        valueFrom:
          secretKeyRef:
            name: firefly-iii-secrets
            key: importerAccessToken
      SPECTRE_APP_ID:
        valueFrom:
          secretKeyRef:
            name: firefly-iii-secrets
            key: saltEdgeAppID
      SPECTRE_SECRET:
        valueFrom:
          secretKeyRef:
            name: firefly-iii-secrets
            key: saltEdgeAppSecret
