# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: global-secrets
    namespace: flux-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:R+fag0wsG9dgTM7sfQXY,iv:nzD8VUmew6eCKFLBTFrZ70i1Q+kW9gqFpDtZdhjFJcM=,tag:wWknMq2xorSCz51LMaFNhg==,type:str]
    SECRET_EMAIL_CLOUDFLARE: ENC[AES256_GCM,data:kq5nWN0qUEezZ4qjrCquqhYSCw==,iv:UWPz1xvMbSHsUomKI+XtcKIfdEpPUOTY2BwWiuHXn30=,tag:IgpSrpwRGsNIxCtJ8NVUoA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7a2rHLlIeyIKZA==,iv:gqSvvqdwEqI63nw/L6AKV8WfG2XvznatPwJtEsGOwb0=,tag:CW65MFNh7tGVK6M/yY31rg==,type:str]
    SECRET_DOMAIN_INTERNAL: ENC[AES256_GCM,data:2PotZX7WY+qx6iN8mA==,iv:jFiXO83Tfo4HHxQGcB0KZkCkmJ14uDLjej7FY4G2eN4=,tag:BN28TxEgK3i+K+j76NEgqw==,type:str]
    TZ: ENC[AES256_GCM,data:E8Xx2yAfNMSDVyxmUkvjbg==,iv:7EGIZEo/U5Z6kMDwDomMQI6ksjz5epPXaEGCuPkKvLM=,tag:Z++bsRzYStPWCBeE0R3Svw==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:nT/BHjS3/7rkv1PNjDi6bMooBw==,iv:p1tUzBuHeKmR1pPS7ywRGGANVapvCuZIRXd4uZjqKsw=,tag:+Jl8GMKkUsPKR9zkB1LEig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbERkZUtLNU5zaW5nT3Qw
            YW5tNTNtR1ErQThCQUhvdlR4R0I5eWpUY3lVCmd6alpvTEJCakhzSDhCSXc0aVlB
            MDhaMzZTL0l4N01HUDdIZWFQZ3JNNVUKLS0tIGdGT0dURlRLUlNXek1PMjNSczh0
            TG80a0FqbXhxRFdqYlNIMHU4ZmpUUUkKAyvusqhSUGbWQlX85NKrFe9ww7I8G3w7
            XgdXbLmVvyF+2KgGbi7I58HfP9G+QlHpNf577EdAqMq78YvPpUfJmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-24T22:55:43Z"
    mac: ENC[AES256_GCM,data:kv7p2oD4nLH/PxHpp0lxLujdv/GDqttOJMuoYRyVm88P6CTvi2UKsqFiZLkMQPdwdGrz7VQOsmhsnr0otLjE8m4fzuVuScQ7HrP8+ttjQISJh33L96EzPSHpv+WaD0mHL3zgnsIxDdJaaK1oF4wCkri4EGHpKxCgLJNreUzUxjU=,iv:jK4KUaoQrl+Fi/Xe7y0R+QfoAk7eItHJa/LP2DahdOk=,tag:Ck/9E72864+dFJEPTh/iQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
