---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &backend-appname sparkleandspin-backend
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *backend-appname
  interval: 10m
  path: "./kubernetes/apps/default/sparkleandspin/backend"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: false
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: ghcr-imagepullsecret
  postBuild:
    substitute:
      APP: *backend-appname
      HOSTNAME: ssbackend.mcgrath.nz
      APP_UID: "568"
      APP_GID: "568"

# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &frontend-appname sparkleandspin-frontend
#   namespace: flux-system
# spec:
#   targetNamespace: default
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *frontend-appname
#   interval: 10m
#   path: "./kubernetes/apps/default/sparkleandspin/frontend"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-cluster
#   wait: false
#   dependsOn:
#     - name: sparkleandspin-backend
#     - name: ghcr-imagepullsecret
#     - name: cluster-apps-external-secrets-stores
#   postBuild:
#     substitute:
#       APP: *frontend-appname
#       HOSTNAME: sparkleandspin.mcgrath.nz
#       APP_UID: "568"
#       APP_GID: "568"
