---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: kube-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://emberstack.github.io/helm-charts
      chart: reflector
      version: 6.1.47
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  interval: 15m
  maxHistory: 2
  timeout: 20m
  install:
    remediation:
      retries: 300
  upgrade:
    remediation:
      retries: 300
  releaseName: reflector
