---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: kube-system
spec:
  chart:
    spec:
      chart: reflector
      version: 6.x
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: reflector
