---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: your-spotify-mongo-data-v1
  namespace: home
  annotations:
    nfs.io/storage-path: "your-spotify-mongo"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-provisioner
