---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs
spec:
  storageClassName: media-nfs
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${SECRET_NFS_SERVER}"
    path: ${SECRET_NFS_MEDIA_PATH}
#  mountOptions:
#    - nfsvers=4.2
#    - tcp
#    - intr
#    - hard
#    - noatime
#    - nodiratime
#    - rsize=1048576
#    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs
  resources:
    requests:
      storage: 8Ti
