---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasmoadmin-v1
  namespace: home
  annotations:
    nfs.io/storage-path: "tasmoadmin"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-provisioner
