---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: miniflux
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: miniflux-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Miniflux
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        OIDC_CLIENT_SECRET: "{{ .BOOKSTACK_OAUTH_CLIENT_SECRET }}" # from authelia
  dataFrom:
    - extract:
        key: bookstack
    - extract:
        key: authelia
