---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/crds
  prune: true
  dependsOn:
    - name: charts
  sourceRef:
    kind: GitRepository
    name: flux-cluster
