---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  chart:
    spec:
      chart: metallb
      version: 0.13.4
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: metallb
  values:
    configInLine:
      peers:
        - peer-address: ${GATEWAY_ADDRESS}
          peer-asn: 65510
          my-asn: 65511
      address-pools:
        - name: default
          protocol: bgp
          avoid-buggy-ips: true
          addresses:
            - ${METALLB_CIDR}
