---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  chart:
    spec:
      chart: metallb
      version: 0.13.4
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: metallb
  values:
    crds:
      enabled: true
    prometheusRule:
      enabled: true
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    speaker:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
      frr:
        enabled: false

    prometheus:
      serviceAccount: kube-prometheus-stack-prometheus
      namespace: monitoring

      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true

  # postRenderers:
  #   - kustomize:
  #       patchesStrategicMerge:
  #         - $patch: delete
  #           apiVersion: admissionregistration.k8s.io/v1
  #           kind: ValidatingWebhookConfiguration
  #           metadata:
  #             name: validating-webhook-configuration
