---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_NAME: "homelab-0"
  CLUSTER_ID: "1"
  METALLB_CIDR: "172.16.10.0/24"
  GATEWAY_ADDRESS: "10.0.16.1"
