# yamllint disable
#
# File contents:
#
# mosquitto.conf: |
#    allow_anonymous false
#    persistence true
#    connection_messages false
#    password_file /mosquitto/configinc/mosquitto_pwd
#    autosave_interval 60
#  mosquitto_pwd: username:password
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto
    namespace: home
stringData:
    mosquitto.conf: ENC[AES256_GCM,data:hokMhc8MGQqjoA0d92NwxBqyDzZeQYXMhwTZZL+LR0uh07f27CWT+vDd+2Rinkjh1MaJmXYwXsiNXxDf4fuItL6NKO+F/I7dK5zESZDUfjaFOJJ34tm09LqJS1Z23Uv+nWEmT79twaFtoveGI2WoHFGpib/ST7BNNmAXJyISwV7RLu+yF/tH,iv:DL+d4YpOit6EnNKxQgaAVXftNswaIqLC9dXunH8YhM4=,tag:JuuAuBHeUkAtEgp1kH4n6Q==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:ms1+VaenV/0X6XZ9z7oXjfBuXOEnpL01/H71FLoSO/uqFYhS/XKRbLpZ22azJoMwSaCuuLm1dCLW+ebKMeni7DqMc4JzBdhUZhJnYxPbF6oqhIepQAVIeAnfLMwyHOYk1KYNYAUyPKNanax4WA==,iv:hrtXgvptZ3S8HpptPA0qqDxpSzWG//zV4zhdVGTrmZc=,tag:AV9dvzQGWUbHIHBsjjbYTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzajJUZGVSczE3eXk0NnVu
            S2xadlpuM0hSZm9kdXRuZitUMXE4c1U1ZEZZCm95UnVXNFZnSjRWamJ0bnZTWElP
            WHFSSjFRYVhXemlqWkUycVZMRXZteTQKLS0tIDMySm85SmdLOHVTcEcrTUNoY0FZ
            OTVIWWJpMFQ2dzEzRFMyMUdGRGZKS2cKMHJgC8XZTQv/zLDUU1gGEeeCPXzrErvW
            qiLUI4iIjTNUwERTzuq6G5RLKkWve+5vBks+gn/2EpbqV1lfTUGEsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T01:37:59Z"
    mac: ENC[AES256_GCM,data:2i9u9PmI1C6pRjOzRxftke8PjwrSFK9G7zvjAgd0jlNcjInmlAlWo0o5LPU+rvahKXRoKsjBAL8o+T8n5f8isirirnrhPI1qcmnkjZqgzZIAN/BQ6LnBS4ndo1o7c9Kga6hJajwtC5RINPkv+/DQ3pSclkorLTkrU4g+rPXFgMk=,iv:1++8NTPSRYxroyS2N4ZlYnfDh7JiFJFCNgQNYVaf9OA=,tag:X5jDQ+VQRv3xhFo3wEo4JQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
