clusterName: home-cluster
talosVersion: v1.1.1
kubernetesVersion: v1.24.3
endpoint: https://10.0.16.131:6443
domain: home-cluster.local
allowSchedulingOnMasters: true
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: custom
  urls:
    - https://raw.githubusercontent.com/bjw-s/home-ops/main/infrastructure/talos/cluster-0/cni/install.yaml
nodes:
  - hostname: rpi1
    ipAddress: 10.0.16.131
    controlPlane: true
    installDisk: /dev/sda
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
  - hostname: rpi2
    ipAddress: 10.0.16.132
    controlPlane: false
    installDisk: /dev/sda
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
controlPlane:
  configPatches:
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
        rotate-server-certificates: "true"
    - op: add
      path: /machine/install/extraKernelArgs
      value:
        - talos.logging.kernel=udp://10.45.0.2:6050/
  inlinePatch:
    cluster:
      aescbcEncryptionSecret: ${aescbcEncryptionKey}
      aggregatorCA:
        crt: ${k8sAggregatorCert}
        key: ${k8sAggregatorCertKey}
      ca:
        crt: ${clusterCert}
        key: ${clusterCertKey}
      etcd:
        ca:
          crt: ${etcdCert}
          key: ${etcdCertKey}
      secret: ${clusterSecret}
      serviceAccount:
        key: ${k8sServiceAccountKey}
      token: ${clusterToken}
    machine:
      ca:
        crt: ${machineCert}
        key: ${machineCertKey}
      token: ${machineToken}
worker:
  configPatches:
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
        rotate-server-certificates: "true"
  inlinePatch:
    cluster:
      aescbcEncryptionSecret: ${aescbcEncryptionKey}
      ca:
        crt: ${clusterCert}
        key: ${clusterCertKey}
      secret: ${clusterSecret}
      token: ${clusterToken}
    machine:
      ca:
        crt: ${machineCert}
        key: ${machineCertKey}
      token: ${machineToken}
