---
clusterName: cluster-0

talosVersion: v1.4.4
kubernetesVersion: v1.27.1
endpoint: https://cluster-0.${domainName}:6443

cniConfig:
  name: none

allowSchedulingOnMasters: true
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - cluster-0.${domainName}

nodes:
  - hostname: hp1.${domainName}
    ipAddress: 10.0.16.132
    controlPlane: true
    installDisk: /dev/disk/by-id/ata-Samsung_SSD_850_EVO_500GB_S2R9NX0H701141P
  - hostname: lappy1.${domainName}
    ipAddress: 10.0.16.133
    controlPlane: true
    installDisk: /dev/sda
  - hostname: lappy2.${domainName}
    ipAddress: 10.0.16.134
    controlPlane: true
    installDisk: /dev/sda


controlPlane:
  patches:
    - "@./customInstaller-patch.yaml"
    - "@./clusterMetricsExtraArgs-patch.yaml"
    - |-
      cluster:
        allowSchedulingOnMasters: true
        apiServer:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        controllerManager:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        discovery:
          registries:
            service:
              disabled: true
        proxy:
          disabled: true
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        scheduler:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True

      machine:
        files:
          - content: |
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
            path: /etc/cri/conf.d/20-customization.part
            op: create
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
            rotate-server-certificates: "true"
          extraMounts:
            - destination: /opt/local-path-provisioner
              type: bind
              source: /opt/local-path-provisioner
              options:
                - bind
                - rshared
                - rw
        install:
          extraKernelArgs:
            - "talos.logging.kernel=udp://172.16.10.5:6050/"
        logging:
          destinations:
            - endpoint: "udp://172.16.10.5:6051/"
              format: json_lines
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - cluster-0.${domainName}
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - 10.0.16.1
