# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-secret
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:yHuWwCEJfoUE4bhCDEts5arFlH+o0V8nqOfzrLtHQqZkmfiE1oG7vGRdicSis4r8NBcmfVQ1KZSx9r8dWEi4HfvZw4oEYbPek2RrNq25gExhENdLr113hP7ucfeRMuva6dWebR+IkgCA6WHWCID7e83DMSVJZem+9ZBpzMRVP5Rfc5UqjJH8bns1KvDpgtRhT34ZiT8o8SZSYK0Ql61UT8sf,iv:husQFELpaADjFJbRuDImubumWD1V5l4ysXEz232wTWk=,tag:/sXy4f+q8gQhz4i5Z4p63A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MStTbnlVVHhKYm11bmcx
            Q3NWaDJMb0pacWN1alNTNkVQb3F0OTdFOFY4CmJGeGRsNDMvMThySnYvbVl1Y3ZK
            OWxLdkdSNklZMnhsMk94OTk3cXY4MEUKLS0tIE1MR1Nsa2x6MVp0R3FJVEVLRCtp
            b0d1djJnakpyeWtLemhTc2RYWXZWa2MKpMihfD+3jLoKq1CDXlaURdyxI0/61bCF
            MnORMD3SYp6TtnEUsIxYF51Rw+9iQ3J8Jv1BFn7LLcIy3qo7hQRnIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-18T05:02:40Z"
    mac: ENC[AES256_GCM,data:fzf7SpEhMmgkCtxKmmRsA6vUzfJChx4KDz1AmVGlcf9kDoQ/Ylc6IzVci6AwP9grCQ7xEAsJWgHksaKMF3d3oAcwtKiM4onnC6+ukFvQTWKotfJQY/mMvJiHY1tuOJ3QN+ef/2Lc0RdiMsLTFIhBrcZ8f7iN9k5YLry7K1or1dE=,iv:On1G5g1n1oIx7l77+sm4+E+uFXEZxXvwNIbC/gpwW+c=,tag:r/tZLNqpr2tFb19D6Xf18g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
