---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: database
spec:
  chart:
    spec:
      # renovate: registryUrl=https://helm.runix.net
      chart: pgadmin4
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: pgadmin4
  values:
    image:
      registry: docker.io
      repository: dpage/pgadmin4
      # Overrides the image tag whose default is the chart appVersion.
      tag: "6.12"
      pullPolicy: IfNotPresent

    env:
      email: ${SECRET_PGADMIN_EMAIL}
      password: ${SECRET_PGADMIN_PASSWORD}

    serverDefinitions:
      ## If true, server definitions will be created
      ##
      enabled: true

      servers:
        brian:
          Name: ${SECRET_POSTGRES_SERVER}
          Group: "Servers"
          Port: 5431
          Username: ${SECRET_POSTGRES_SERVER_SUPERUSER}
          Host: ${SECRET_POSTGRES_SERVER}
          SSLMode: "prefer"
          MaintenanceDB: "postgres"

    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - host: &host "pgadmin.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: "wildcard-tls"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: database-cog
        hajimari.io/appName: PGAdmin
        hajimari.io/group: Database
    persistentVolume:
      enabled: true
      existingClaim: pgadmin-v2
