---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data-v1
  namespace: home
  annotations:
    nfs.io/storage-path: "frigate"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-provisioner
