kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: frigate-secrets
    namespace: home-automation
stringData:
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:HwD3RiILNUcoEUuGUQ9xY60c24EP57k9,iv:O/dMC0tDEhaxilvf57zaOPKKQ7gkw+sOHRQmFq2nqG0=,tag:G7T+AtJZcFapbDlG/O6+Cw==,type:str]
    FRIGATE_CAMERA_FDC_HOST: ENC[AES256_GCM,data:GFcRc/RQIvAhiA==,iv:B27vufFPjeJIAeT7w8VyVj+JEjO3bIkv49dNiGMRns8=,tag:EsGCMDM4VkNT59BdD764BA==,type:str]
    FRIGATE_CAMERA_FDC_USER: ENC[AES256_GCM,data:dCwDEHg=,iv:pzOddOdx/HzIp6rQiMeJjW3yMyXEBje5P3cPUURO6Pg=,tag:sjoTObmGzNGnzbBoB7vIWg==,type:str]
    FRIGATE_CAMERA_FDC_PASSWORD: ENC[AES256_GCM,data:RMnIfFA1WGPSVVS0tqj8rmWv6Mu1D+KPdtpTQyDz75d80M34h2I=,iv:y7B/2e0rHPqkWgGF0roWEgt4aWbtVHcBTbDKoFEKOOQ=,tag:3m9LQ+oz04Ou4toS8TwqTA==,type:str]
    FRIGATE_CAMERA_BDC_HOST: ENC[AES256_GCM,data:iYWR2mAoPzPIOQ==,iv:TNSIHkh8gfGcKcvh1qM2QLjkC9tT/VqmbQWpxOXy5X4=,tag:58VFNKMp8bHXEfvFYjw1YA==,type:str]
    FRIGATE_CAMERA_BDC_USER: ENC[AES256_GCM,data:RRx4U0Q=,iv:djKvIFHTFej777XFsRWZsZjEUoYyr9Pn2mfDFvbGg70=,tag:B1PUJrTu/A13bxZ58hgOVw==,type:str]
    FRIGATE_CAMERA_BDC_PASSWORD: ENC[AES256_GCM,data:uUz8vGxddjrz2+/6sbxRbOuTPY5A1DYWDdPAEYsks4v6wJoajtQ=,iv:WLezNtwkImsWnYYa/broORe9cBLtwbzGMODHiF0g+pk=,tag:g88v4h76XpkinQJrbw4rvg==,type:str]
    FRIGATE_CAMERA_SDC_HOST: ENC[AES256_GCM,data:KrU5CRM0zw/J6Q==,iv:7mz4+RCYAfArFzTPcmxFMGQeiB9QOsFLYRBpDNXt72U=,tag:uc/uCiBCuZGcogjFMfWpbQ==,type:str]
    FRIGATE_CAMERA_SDC_USER: ENC[AES256_GCM,data:miTX+Lo=,iv:0F341NL0v/cySOhefuRlyS1Ym60i8pSQ4WiRGKqsf2E=,tag:iQz2qG3GZjsR1td5ID1X7w==,type:str]
    FRIGATE_CAMERA_SDC_PASSWORD: ENC[AES256_GCM,data:deHjRUsFtN5AZLqc8tsEWcoJk69AR18hmE22w0n6i08jUYXhsbo=,iv:EsNnuN+16VIXCA54kytHzEO3ZH0Dg38SBMKfZR9XuGc=,tag:OunuvRcGkXqEr0JaOLkNQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMnJxMXNDaUtBSmFzRHRj
            MDJUNGIrR043L1k3VXh0WTdsZlprUjYzNHljCkF6ZHI0aWZLUGZoR1dxMU04RzNq
            YU1iREoxNjJPNjBteDA3aW5WMERYMWMKLS0tIDNUUE1JRDRHdmdjaUtvUDZXS3hI
            U2VPd0pxeHRHb1NlWUFhWnFtWDUzSnMKdiDzILKeMhpuiVqP91nVJyUUAU1r44aH
            CgH8FLhClGP/iCp/yX7c1LqqnG/5+ZjVhU5m4t/QKrnjBL24wk9tLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-11T22:08:25Z"
    mac: ENC[AES256_GCM,data:0U69Rh1/zfc4PLM0UrSJsoj8uMxhLDz5ZIgxsUJNBEgO+ZX8a8Hj1izqcK8CTcRSGas7o/nBQFl9dfpfkVNlwXSliB3pUUuX98DgirU1oBFwMdyo7lukHnXTZoYFIyKS108MYxOESD2j+FlfZ7C0SnLgIf0b066pGG+vRD+WnAE=,iv:9knvKoADDZX20/ZlKVECu2hCZBJUZOdgdEpgRWO1rHU=,tag:w87IWFonFzyEQ7PwHNZXQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
