kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: frigate-secrets
    namespace: home-automation
stringData:
    PLUS_API_KEY: ENC[AES256_GCM,data:r7HbQYdzAGywXC2G3HEaOwet55DKZg5qhuK8tt1QB5crIzYJOngB8k4ddc73xZRJXNSt1tnKWX+hqzSCa+MxuGRA/S92sQX4H9hC0kU=,iv:hPoza7glo3yhKMdxrDBGHoE9+dL6KdYFbJgBcpPw9Rc=,tag:CLkwhWfAoitc+Y9tLboRbQ==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:HwD3RiILNUcoEUuGUQ9xY60c24EP57k9,iv:O/dMC0tDEhaxilvf57zaOPKKQ7gkw+sOHRQmFq2nqG0=,tag:G7T+AtJZcFapbDlG/O6+Cw==,type:str]
    FRIGATE_CAMERA_FDC_HOST: ENC[AES256_GCM,data:GFcRc/RQIvAhiA==,iv:B27vufFPjeJIAeT7w8VyVj+JEjO3bIkv49dNiGMRns8=,tag:EsGCMDM4VkNT59BdD764BA==,type:str]
    FRIGATE_CAMERA_FDC_USER: ENC[AES256_GCM,data:dCwDEHg=,iv:pzOddOdx/HzIp6rQiMeJjW3yMyXEBje5P3cPUURO6Pg=,tag:sjoTObmGzNGnzbBoB7vIWg==,type:str]
    FRIGATE_CAMERA_FDC_PASSWORD_ESCAPED: ENC[AES256_GCM,data:POPFJzfgRcLtQYISrj/1RGPD2L2HgrizD7xoTP410uzLhYwrgyk=,iv:lrAc3ruf0zC0ZRdn9+EzeV6LbwKHeSccs64WEB60oEg=,tag:4ivdeCply6FuDqaqrmccqA==,type:str]
    FRIGATE_CAMERA_FDC_PASSWORD: ENC[AES256_GCM,data:mZTcpem1tnIu/ZYF91VCScOmNrfeYTn6RTR4nkId,iv:uTAZjE0qtkOZJNcpqXgBAHubN+Foyhw40vIpv7nCyfk=,tag:2o+I8IjIuf6GErE71xix7A==,type:str]
    FRIGATE_CAMERA_BDC_HOST: ENC[AES256_GCM,data:iYWR2mAoPzPIOQ==,iv:TNSIHkh8gfGcKcvh1qM2QLjkC9tT/VqmbQWpxOXy5X4=,tag:58VFNKMp8bHXEfvFYjw1YA==,type:str]
    FRIGATE_CAMERA_BDC_USER: ENC[AES256_GCM,data:RRx4U0Q=,iv:djKvIFHTFej777XFsRWZsZjEUoYyr9Pn2mfDFvbGg70=,tag:B1PUJrTu/A13bxZ58hgOVw==,type:str]
    FRIGATE_CAMERA_BDC_PASSWORD: ENC[AES256_GCM,data:nNWYBBuPZTkB5r7w5IZenBWuuJ/qczRDa4lI4vuS,iv:iiiE9Ct/B3ZKjntqyv/WohjdCH0fR9tipId4vhWOfyM=,tag:lNWsSl3QacsMt3VpoZFapQ==,type:str]
    FRIGATE_CAMERA_SDC_HOST: ENC[AES256_GCM,data:KrU5CRM0zw/J6Q==,iv:7mz4+RCYAfArFzTPcmxFMGQeiB9QOsFLYRBpDNXt72U=,tag:uc/uCiBCuZGcogjFMfWpbQ==,type:str]
    FRIGATE_CAMERA_SDC_USER: ENC[AES256_GCM,data:miTX+Lo=,iv:0F341NL0v/cySOhefuRlyS1Ym60i8pSQ4WiRGKqsf2E=,tag:iQz2qG3GZjsR1td5ID1X7w==,type:str]
    FRIGATE_CAMERA_SDC_PASSWORD: ENC[AES256_GCM,data:MvcgsaKg5zvNV4PtaODKj7yRPYuza+0GzSUBGOhi,iv:QlMZ5OQjXUkxJN2AhMQIOt0c6Q7CcGMkf8xjxHnqwqQ=,tag:vMpF8UgywxI8oxBEizMdpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMnJxMXNDaUtBSmFzRHRj
            MDJUNGIrR043L1k3VXh0WTdsZlprUjYzNHljCkF6ZHI0aWZLUGZoR1dxMU04RzNq
            YU1iREoxNjJPNjBteDA3aW5WMERYMWMKLS0tIDNUUE1JRDRHdmdjaUtvUDZXS3hI
            U2VPd0pxeHRHb1NlWUFhWnFtWDUzSnMKdiDzILKeMhpuiVqP91nVJyUUAU1r44aH
            CgH8FLhClGP/iCp/yX7c1LqqnG/5+ZjVhU5m4t/QKrnjBL24wk9tLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T21:35:24Z"
    mac: ENC[AES256_GCM,data:4d54AX6GHM+PCmMciSO0ffr+l85wpgND53YcpDMzfjcQ8tDtvXR0jXJC6JcofnA2ykby24qTT9C1ctOpInCrPlqKZFfRNnzMiOlLxVq7M+ujS1mzXaRCC5WqG4+jcsELVfB2fgIbK/zq9z0MSqb0kos+xLhs849SgPi+H6Wehes=,iv:iHYTtjzZiS0Xu0ottDUYCPoqMvVyP0semfoBBguNuwQ=,tag:RzhgimHCwVDKJbI4B/1YYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
