kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: frigate-secrets
    namespace: home-automation
stringData:
    PLUS_API_KEY: ENC[AES256_GCM,data:r7HbQYdzAGywXC2G3HEaOwet55DKZg5qhuK8tt1QB5crIzYJOngB8k4ddc73xZRJXNSt1tnKWX+hqzSCa+MxuGRA/S92sQX4H9hC0kU=,iv:hPoza7glo3yhKMdxrDBGHoE9+dL6KdYFbJgBcpPw9Rc=,tag:CLkwhWfAoitc+Y9tLboRbQ==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:HwD3RiILNUcoEUuGUQ9xY60c24EP57k9,iv:O/dMC0tDEhaxilvf57zaOPKKQ7gkw+sOHRQmFq2nqG0=,tag:G7T+AtJZcFapbDlG/O6+Cw==,type:str]
    FRIGATE_CAMERA_FDC_HOST: ENC[AES256_GCM,data:GFcRc/RQIvAhiA==,iv:B27vufFPjeJIAeT7w8VyVj+JEjO3bIkv49dNiGMRns8=,tag:EsGCMDM4VkNT59BdD764BA==,type:str]
    FRIGATE_CAMERA_FDC_USER: ENC[AES256_GCM,data:dCwDEHg=,iv:pzOddOdx/HzIp6rQiMeJjW3yMyXEBje5P3cPUURO6Pg=,tag:sjoTObmGzNGnzbBoB7vIWg==,type:str]
    FRIGATE_CAMERA_FDC_PASSWORD: ENC[AES256_GCM,data:MOo/UA7htORGEFZ6NgmACUK7fx4=,iv:ipygyyy5zuM9lf978NWIIkvQyVI0wuFxFxMyPEvBS8o=,tag:+JwL0+P6GIKFWlMTAAAfUw==,type:str]
    FRIGATE_CAMERA_BDC_HOST: ENC[AES256_GCM,data:iYWR2mAoPzPIOQ==,iv:TNSIHkh8gfGcKcvh1qM2QLjkC9tT/VqmbQWpxOXy5X4=,tag:58VFNKMp8bHXEfvFYjw1YA==,type:str]
    FRIGATE_CAMERA_BDC_USER: ENC[AES256_GCM,data:RRx4U0Q=,iv:djKvIFHTFej777XFsRWZsZjEUoYyr9Pn2mfDFvbGg70=,tag:B1PUJrTu/A13bxZ58hgOVw==,type:str]
    FRIGATE_CAMERA_BDC_PASSWORD: ENC[AES256_GCM,data:s4PviHgpfeHW0+/COLyMkym/Gro=,iv:LhDFlRaQS5HQKOYpWgJCgZpw7hZ1Vd3GZ1Jol3BQFng=,tag:Y8TuEUv0hIsRgdwIrttXrg==,type:str]
    FRIGATE_CAMERA_SDC_HOST: ENC[AES256_GCM,data:KrU5CRM0zw/J6Q==,iv:7mz4+RCYAfArFzTPcmxFMGQeiB9QOsFLYRBpDNXt72U=,tag:uc/uCiBCuZGcogjFMfWpbQ==,type:str]
    FRIGATE_CAMERA_SDC_USER: ENC[AES256_GCM,data:miTX+Lo=,iv:0F341NL0v/cySOhefuRlyS1Ym60i8pSQ4WiRGKqsf2E=,tag:iQz2qG3GZjsR1td5ID1X7w==,type:str]
    FRIGATE_CAMERA_SDC_PASSWORD: ENC[AES256_GCM,data:1u6ZL6IUgbVk/RgqwwGgAJw0a4E=,iv:1wUhlFxneBe0TlB3nil2TuiCB7vRMKuXUVUoXnI+J3Y=,tag:HxGMxyNUhOTaC+jcruIx6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMnJxMXNDaUtBSmFzRHRj
            MDJUNGIrR043L1k3VXh0WTdsZlprUjYzNHljCkF6ZHI0aWZLUGZoR1dxMU04RzNq
            YU1iREoxNjJPNjBteDA3aW5WMERYMWMKLS0tIDNUUE1JRDRHdmdjaUtvUDZXS3hI
            U2VPd0pxeHRHb1NlWUFhWnFtWDUzSnMKdiDzILKeMhpuiVqP91nVJyUUAU1r44aH
            CgH8FLhClGP/iCp/yX7c1LqqnG/5+ZjVhU5m4t/QKrnjBL24wk9tLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T21:44:11Z"
    mac: ENC[AES256_GCM,data:S2RBNL/3PTk2LpZ/KSBbxYxS5K0XqzBiBD13RvCQjuGhP2l52RTHcoJd4+2Nwee1YP02v4UOx5NvQ5aLjPop+uScENxLgTRTq1rN3Rp5FrF76rHBLO+mmhYX+cv9gb7jjd3STXnYqQboKQJQl7PJaJmQaVdUYE0dt2zwyeOyhJE=,iv:MpBmBZQp5mDsYth9qaPIZ6pgCKdhx7j2VhK5SEirDDk=,tag:7AXDFQg51X4fBWLqs5zsEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
