# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-token-secret
    namespace: networking
stringData:
    tailscale-token: ENC[AES256_GCM,data:nViLP9fnNPaESkaF/eDdHJ+XJQnyhTK4rBDmzqkHgPPp6r5XRvqG0DRCQpIJ8QpVQUNPJWy1KcY=,iv:h09qIR6Agd4VWU+WH1NHEAWTCgg28O+oV5WGQ6hjtGI=,tag:b7fA7kQbVZqsLbtaMi8UCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdTdzbHJKdWxRc1R0NXAy
            czE0NXFTQjE5R1Zaa2VSNytTZWJmaW9pblFBClI2QmVzTGw5WTF5SGo2czljY0l3
            WHVzRVFkVmZnb0hUdEMwb2dLNEZSMDgKLS0tIGFOVnpERnNmY3pMdW9NRDNQRWk3
            ZTJOckUyRVQ2K0FiUEIvTjdoTW1qbzQK7cllUwLjkinv3/DPfeyf7spuiruANx0S
            jFSiPn5tynifCRI2FWBDB4kVFjMyhW3Wd0UvGwpj4MMl4wZt6uXDbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-14T20:30:44Z"
    mac: ENC[AES256_GCM,data:0JukGpjvsD/d3E2lt2EquAd9CKUiR6BYEMiNiUD9eUHtws4EgpxTVPMgQUnMjh60O7SvmBCzrFXfjWb/ClcHADZw1lEwInkX0YL7LfnjNY2nwgXKru+CTOnfqJWsgfBieqbojraYQsdGNfVo2fgQf5xBfmf+noFssIQ0kf20Buw=,iv:jJGHSmbmXDckVy4TftZO1W/6V4S1+FkigPQKq3krQi0=,tag:BSo90EV03BlcotGxM1dUrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
