---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-v2
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
