---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-v1
  namespace: media
  annotations:
    nfs.io/storage-path: "sonarr"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-provisioner
