---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: phpmyadmin
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: phpmyadmin
      version: 10.2.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      # Changed from bitnami image to support ARM64
      registry: docker.io
      repository: phpmyadmin
      tag: 5.2.0-fpm-alpine
      pullPolicy: IfNotPresent
    db:
      allowArbitraryServer: false
      host: ${SECRET_MARIADB_SERVER}
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: &host phpmyadmin.${SECRET_DOMAIN}
      pathType: Prefix
      path: /
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: database-cog
        hajimari.io/appName: phpMyAdmin
        hajimari.io/group: Database
      extraTls:
        - hosts:
            - *host
          secretName: wildcard-tls
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
