---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: phpmyadmin
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: phpmyadmin
      version: 10.2.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    db:
      allowArbitraryServer: false
      host: ${SECRET_MARIADB_SERVER}
    ingress:
      enabled: true
      hostname: phpmyadmin.${DOMAIN}
      pathType: Prefix
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: database-cog
        hajimari.io/appName: phpMyAdmin
      tls: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
