---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./volsync.yaml
  - ./nfs-pvc.yaml
  - ../../../../templates/gatus/external
labels:
  - pairs:
      app.kubernetes.io/name: plex
      app.kubernetes.io/instance: plex
      app.kubernetes.io/part-of: plex
