---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-nfs
spec:
  storageClassName: plex-nfs
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.20.0.1
    path: /volume1/Media/
  # Note: The first two options are strictly for NFSv4.2
  #mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-nfs
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: plex-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
