---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: home
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mealie
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8sathome
        namespace: flux-system
  interval: 15m
  maxHistory: 2
  timeout: 20m
  install:
    remediation:
      retries: 300
  upgrade:
    remediation:
      retries: 300
  releaseName: mealie
  values:
    image:
      repository: hkotel/mealie
      tag: frontend-v1.0.0beta-3
      pullPolicy: IfNotPresent
    api:
      image:
        repository: hkotel/mealie
        tag: api-v1.0.0beta-3
        pullPolicy: IfNotPresent
      env:
        TZ: ${TIMEZONE}
        TOKEN_TIME: 43830
        DB_ENGINE: sqlite
        POSTGRES_USER: ${SECRET_MEALIE_PG_USER}
        POSTGRES_PASSWORD: ${SECRET_MEALIE_PG_PASS}
        POSTGRES_SERVER: ${SECRET_MEALIE_PG_SERVER}
        POSTGRES_PORT: 5431
        POSTGRES_DB: ${SECRET_MEALIE_PG_DB}
        BASE_URL: https://mealie.${SECRET_DOMAIN}
    env:
      TZ: Pacific/Auckland
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
          hajimari.io/enable: "true"
          hajimari.io/icon: food
          hajimari.io/appName: Mealie
          hajimari.io/group: Home
        hosts:
          - host: &host mealie.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: wildcard-tls
            hosts:
              - *host
    persistence:
      api-data:
        enabled: true
        existingClaim: mealie-v2
