---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-v2
  namespace: home
  annotations:
    nfs.io/storage-path: "mealie"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-provisioner
