---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: home
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    hajimari:
      namespaceSelector:
        matchNames:
          - database
          - home
          - media
          - monitoring
          - networking
      name: Diaoul
      customApps:
        - name: NAS
          url: https://${SECRET_NAS_HOSTNAME}
          icon: nas
        - name: 3D Printer
          url: https://3dp.${SECRET_DOMAIN}
          icon: printer-3d
      groups:
        - name: Tech
          links:
            - name: Hacker News
              url: https://news.ycombinator.com/
    ingress:
      main:
        enabled: true
        annotations:
        hosts:
          - host: &host hajimari.${DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: hajimari-tls
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-data
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 500Mi
