---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homebox-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: homebox
        group: internal
        url: https://homebox.mcgrath.nz
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          insecure: true
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
