# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-secret
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:gP9NVhDydiBJiQvnz5/ui7fMkAFtQjxTXBooj/pikDGwrS3cFHynlO9XeBhtF2dRV36dzFrdwSQ6IoN/znPbeuzrvM/Quxh/H3u9gLKBVyeGi2ZtSJu6OJGIxFayKfbfG7HI8zbr6gFhDpYw7rDky0TdXXEtVMRsRhuO+xWemRe0Wf/Csol7jUN6Qf//MlBn7UoaTEkbZBj+4yx7,iv:pa7Z6YHrHzdxx26EJ3EhRl1Ip2LtYYZAkGIHpqN1mBQ=,tag:lKe+IYHTkwQbAUElviq2kQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSW9yeGRRcjhqMVdmVHNG
            bHkxMFBIeEtZOGR3RGRzNnlGdHZLdnhRdFFrCjBYeEQ5UFRCMzhlYzVVLzFxWjlw
            TWVPLzBvdGZ2M3htajNoeTVZRkRNbVkKLS0tIGZEc3Q5UTF5QUVjV0V6engxQWY3
            ZlBrN3JDcGJoaVRUWVJMckNUbVhKSEUKQZccc2+VsKWD8x0KI0P+quMWg0ZmJB4r
            m7sc0oImHWGg1sfh9BKhSYkvniFt0z09EOhDSN7ZVk+DmpgOcbdKyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-18T05:01:23Z"
    mac: ENC[AES256_GCM,data:5RrGYch5C2noVcsGbOnL7Lh0z5FhmKhBqXUdamBAVXuW0d5IwJoopHEBOoxA1NrEFX0EDcNJjH1gZPf1ZzeaUeAPS21qQv6QuUV+pOsdEev5pFVyvtMpZL+J4cl3F4TSXf1kwKiH0VK+f3EJMbrQ5DKvBOIaRJdgwXYgkFa3O3U=,iv:Jd7jdXZt7M8f42S0KrBe3ZZef5005ePAz1/+nWqNHcI=,tag:2k5GQxsNUesY90W9W4eyqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
