# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-secret
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:4aEIOaz5uwrBj48mreeGKwzboyVRbdlkHdUDZQL5NH9xCR2c1vI7UkYZCYrUGx9Dxwgl+ymUffMhJGY/JUkuIgtikun0/NzNFCm5+jtsH8TeNKD3rSweKxdSb7ikdAaGCbGzoTwLA8v+GUrJZIE6BDdjfpEgK+oa1uypow/kVosi0r19qMvekt8XK3ypM5XSESEP+LWerc7koQW9l4n6T0Dxrnl3,iv:K4QfNag5kO5kLBymjD/L9fbrD3Bi221ilIcghaB8IsU=,tag:GEEOqqknF24x3WDhbEJRtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bWplOFFtYlNCTXdUQlRN
            SVNwRUQ1d0swZWQxOHptM29BaTFVaWYzTmxJCnZXNzNtRC8vbStHVkhPeUJTRjJC
            MFIzZ3ByaHQ4ZkxoTmZMcTd5Qmd4d2sKLS0tIGRWRzQraW04REZlNHFVMUVqc2VW
            bjJEK2IwblZrQWVGNmRKRmJQUHp4bDgKM6zVhdEB2XRAHVxsmIMVLSnEDBXHJHxk
            CtfVtZC3EGnzvVtWT4qFhpSLc7zkbTgN5BA8GRlzYgqPGjE5z+HTfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-17T23:40:22Z"
    mac: ENC[AES256_GCM,data:tAVxOYi+8Eb0qnpwjAgpXmyZVUgy4W0Por/zRyy32tEoqgqA0Ow5KwtXi+XriNoQEuz8CQV2Z3JKxbLjm4paVwbiQsUwaF3CdEM5l4ZXN9mIq0S/kB2D3i6sGDI+A9ojGIy9ncYlGWM8tJbjcPSKI5uMiVxk6dywjWkmOZe0jiY=,iv:1HQK8SoMTpPyhUenVzb77mtk/AK5++4SYXz25Nv4m38=,tag:JFHhgD/WrvLZPY6k5LZeag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
