---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-redis
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.2.3@sha256:9ff9dca62ed50fd7697ef300888326a303199f9db183f25aabc8e45999532159
            env:
              REDIS_REPLICATION_MODE: master
            resources:
              requests:
                cpu: 5m
                memory: 256M
              limits:
                memory: 256M
    service:
      main:
        ports:
          http:
            enabled: false
          redis:
            enabled: true
            port: 6379
