---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-lb
  namespace: networking
spec:
  ipAddressPools:
    - bgp-pool
  peers:
    - gateway
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: gateway
  namespace: networking
spec:
  peerAddress: ${GATEWAY_ADDRESS}
  peerASN: 65510
  myASN: 65511
  holdTime: 1m30s
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: bgp-pool
  namespace: networking
spec:
  addresses:
    - ${METALLB_CIDR}
