# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-secret
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:Gb68RDhrADdoLxBRcf9xmITmd6xV/iEraqxz+KkSGIRGwqpWxSRBiCXWTDYAoa+bqp/10WSX+Y3zNHAAjj2mxQUNMp1bz5ik8IJs1llGbTppf8A0cx22yOF8HtnZQFfcoZ82ufoYnIF58LSvf7hHJvZQUTUoYFf/CpY0EhLxEMbl73JAeUna3YUVLPP1+cF7JTUMjqPfVq4626dv,iv:k9r5T8fU6FNyPGBxIMSRhvO+Mwczx6Zbn2NwiP0comE=,tag:GFHFoq5DWtl0BDQybgqctw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MStTbnlVVHhKYm11bmcx
            Q3NWaDJMb0pacWN1alNTNkVQb3F0OTdFOFY4CmJGeGRsNDMvMThySnYvbVl1Y3ZK
            OWxLdkdSNklZMnhsMk94OTk3cXY4MEUKLS0tIE1MR1Nsa2x6MVp0R3FJVEVLRCtp
            b0d1djJnakpyeWtLemhTc2RYWXZWa2MKpMihfD+3jLoKq1CDXlaURdyxI0/61bCF
            MnORMD3SYp6TtnEUsIxYF51Rw+9iQ3J8Jv1BFn7LLcIy3qo7hQRnIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T03:51:29Z"
    mac: ENC[AES256_GCM,data:XUrx/1IPV7ANkYKMyIfDFXVHTEl3myAmGDFD0HCxf9VU6Guy2AniJtGMH82sezK/Y3ZgEmi9U0K3z+U6TVuj1TQbNZwDzL1sYa3GAtHwr0F1kYiD3R55ekkCgL2oQZckf5quMYLwXNB763FnKeo3JWEyyZNAfti0Spyhy7Cy5PY=,iv:3lqszAS7CsPKprrHzGNsdHssUPzvpJ6LtKsGNnsqQxE=,tag:sYJ2/sQaznHuX5XonAWZcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
