---

- name: Install K3s and prerequisites
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: k3s/prereq
    - role: k3s/download
    - role: k3s/raspberrypi

- name: Configure K3s master nodes
  hosts: master
  become: true
  roles:
    - role: k3s/master

- name: Configure K3s worker nodes
  hosts: workers
  become: true
  roles:
    - role: k3s/node

# - name: Set up MetalLB
#   hosts: localhost
#   environment:
#     KUBECONFIG: ./kubeconfig.yaml
#   roles:
#     - k3s/metallb
