---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-v2
  namespace: database
  annotations:
    nfs.io/storage-path: "pgadmin"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-provisioner
