---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: default
data:
  TZ: Pacific/Auckland
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.default.svc.cluster.local:3003
  IMMICH_SERVER_URL: http://immich-server.default.svc.cluster.local:3001
  IMMICH_WEB_URL: http://immich-web.default.svc.cluster.local:3000
  LOG_LEVEL: verbose
  # {"db":15,"sentinels":[{"host":"redis-node-0.redis-headless.default.svc.cluster.local","port":26379},{"host":"redis-node-1.redis-headless.default.svc.cluster.local","port":26379},{"host":"redis-node-2.redis-headless.default.svc.cluster.local","port":26379}],"name":"redis-master"}
  # base64 encode that string
  REDIS_URL: ioredis://eyJkYiI6MTUsInNlbnRpbmVscyI6W3siaG9zdCI6InJlZGlzLW5vZGUtMC5yZWRpcy1oZWFkbGVzcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwicG9ydCI6MjYzNzl9LHsiaG9zdCI6InJlZGlzLW5vZGUtMS5yZWRpcy1oZWFkbGVzcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwicG9ydCI6MjYzNzl9LHsiaG9zdCI6InJlZGlzLW5vZGUtMi5yZWRpcy1oZWFkbGVzcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6InJlZGlzLW1hc3RlciJ9
  TRANSFORMERS_CACHE: /usr/src/app/.transformers_cache
  TYPESENSE_DATA_DIR: /config
  TYPESENSE_HOST: immich-typesense.default.svc.cluster.local.
