---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: immich
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich
spec:
  storageClassName: immich
  capacity:
    storage: 1Mi # Size does not matter ...twss
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.16.16
    path: /volume1/Data/Immich
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: immich
  resources:
    requests:
      storage: 1Mi # Size does not matter ...twss
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-config
  namespace: default
  labels:
    app.kubernetes.io/name: &name immich
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
