---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app smokeping
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/linuxserver/smokeping
      tag: 2.7.3
    initContainers:
      01-init-config:
        image: ghcr.io/onedr0p/alpine:3.17.3@sha256:e6a2407a15b7e557fb6617a592f672b004b6764887438502c047a567ec616e40
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["cp /configmap/* /config"]
        volumeMounts:
          - name: configfiles
            mountPath: /configmap
          - name: config
            mountPath: /config
    env:
      TZ: ${TIMEZONE}
      PUID: "1000"
      PGID: "1000"
    service:
      main:
        ports:
          http:
            port: &port 80
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "tunnel.mcgrath.nz"
          hajimari.io/icon: mdi:rss
        hosts:
          - host: &host "ping.mcgrath.nz"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
    persistence:
      config:
        enabled: true
        type: emptyDir
        mountPath: /config
      configfiles:
        enabled: true
        type: configMap
        name: smokeping-configmap
        mountPath: "-"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
