---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: xteve
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: xteve
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8sathome
        namespace: flux-system
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    image:
      repository: alturismo/xteve
      tag: latest@sha256:7885f2759c0da3c5f2c72b2e45ba4b602bdd7d6f04cc6abba201091f11c93a95
    updateStrategy: Recreate
    env:
      TZ: "${TZ}"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_XTEVE_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 34400
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "xteve.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "xteve.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: xteve-config-v1
    nodeSelector:
      kubernetes.io/hostname: "hp1"
