---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nodefeaturerule.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./volsync.yaml
  - ../../../../templates/gatus/guarded
configMapGenerator:
  - name: frigate-configmap
    files:
      - config.yaml=./config/config.yaml
generatorOptions:
  disableNameSuffixHash: true
