---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.2@sha256:3436dfbbc2799332a01361e007e3b408d016cfc235261e1caccc65e6edadf516
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: home-assistant-secret
        containers:
          app:
            image:
              repository: ghcr.io/wipash/home-assistant
              tag: 2024.5.2@sha256:7b6b4ede9165376295c03f300962bf4ce7dd35ff4d005bbcca58f2a9831fd261
            env:
              TZ: Pacific/Auckland
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.23.1@sha256:897b358eed18114061b371f2b2f1416bc7acbed9442877428ecc0855523031ad
            args:
              - --auth
              - none
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - --port
              - "8080"
              - "/config"
            env:
              TZ: Pacific/Auckland
            envFrom:
              - secretRef:
                  name: home-assistant-code-secret

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: home-assistant
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SVC_HOME_ASSISTANT_ADDR}
        ports:
          http:
            port: 8123
          mdns-tcp:
            port: 5353
            protocol: TCP
            targetPort: 5353
          mdns-udp:
            port: 5353
            protocol: UDP
            targetPort: 5353
          sonos:
            port: 1400
          code-server:
            port: 8080
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.mcgrath.nz
          nginx.org/websocket-services: home-assistant
        hosts:
          - host: &host hass.mcgrath.nz
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
      code-server:
        enabled: true
        className: internal
        hosts:
          - host: "ha-code.mcgrath.nz"
            paths:
              - path: /
                service:
                  identifier: app
                  port: code-server
    persistence:
      config:
        existingClaim: home-assistant
        globalMounts:
          - path: /config

      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
