apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCmW/ngd2IQPFEX1Dr4Id960tfjN6ZEzpTNZ6kcgIR2HG3JtR7M+IOFCkLckbJlQJAeRrO1m7Lh8GQbn93uS2CfuA7moQjLtM5e0IwC6lDpXVPdsIWr8Pl0G55ycxShzyLX7xOWt+3I/FeEjNo2s3aYDkSUT6mLKjZDrkG/Bl/tXOXjFG/6WQ+4c4tOnm5tPYkIy4ft8CFBX0B0evqUL/JJ0TpKgwJdrnsoCRQ9BoPXUZUf6M3DMA9PlW06IwY63Y/uMBwyejiMCb0m23izYf3QemvIxsvj5Ft3QXeHZP49nXkbTy3exvnnEsnoh+gN0oM3/G4sOmqRqv/BxTfHjKd1r/2ukNcQoJ17azQPDTpAZE2iYkOM5vmUb8PglOr+fSLUDaKSMG584nFNDUjozClXGw5JMDm3EnY9Yu+E6XVtZBYDq8+M0ecK0b3kmCr7LBAii1YhAN+Flejb/7aySZEM5CJGWBnMjafBdIvofaThrk8hAnyMQOqI/UsYIgSQnQmd5hj4ce6o7asJotTMALIDFoI4IxyZL4n9VqvDRd7IuxuPrSP2zRwIxari9iNkPnmeBphMR7weR9TLSXuvw1kB50F/iCYtmVST2YKQDAcO3vWmfW6pIE/DB9akxwNuoaD409i/NVA8AyphIU4+XQK43/FUEUD6d7lJfTp3Mw/Eogc8dyLjTX/pYX9spiZ7o731zwHotjOmZDG4zH36tOVOgpu9Gmbb1mo5/7rcI0qBgDYXzaKkPqWl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

