---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-v1
  namespace: media
  annotations:
    nfs.io/storage-path: "radarr"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-provisioner

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-v2
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
