---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-filebrowser-foundry
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  path: './kubernetes/apps/services/filebrowser-foundry/app/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: filebrowser-foundry
      namespace: default
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-foundryvtt
